INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (81,"Lara Horton","Placerat Eget Venenatis Ltd","2021-07-14 01:43",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (78,"Roary Salas","Dictum Mi Ac Industries","2021-07-16 17:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (95,"Courtney Melendez","Vel Turpis Aliquam PC","2021-07-14 06:23",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (19,"Ifeoma Sheppard","Aliquam Tincidunt Ltd","2021-07-14 04:47",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (29,"Breanna Olsen","Dapibus Rutrum Justo Foundation","2021-07-13 14:18",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (47,"Otto Wells","Erat Ltd","2021-07-16 00:59",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (45,"Honorato Horn","Adipiscing Lacus Inc.","2021-07-16 12:26",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (40,"Jamalia Schwartz","Tempor Arcu Vestibulum Inc.","2021-07-15 10:31",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (14,"Ruby Peters","Dolor Associates","2021-07-15 19:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (51,"Iona Sloan","Enim Curabitur Consulting","2021-07-13 15:46",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (90,"Leonard Merrill","Tellus PC","2021-07-12 02:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (100,"Rina Moore","Nec Incorporated","2021-07-16 21:51",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (99,"Noelani Vance","Fringilla Est Mauris Associates","2021-07-12 14:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (49,"Hermione Bryant","Faucibus Leo LLP","2021-07-14 13:35",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (30,"Samuel Barron","Vehicula Pellentesque LLP","2021-07-16 21:04",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (89,"Quin Rollins","Odio Sagittis Limited","2021-07-15 06:49",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (84,"Porter Roberson","Ornare Associates","2021-07-13 18:08",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (91,"Brian Terry","Maecenas Libero Est LLC","2021-07-13 04:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (94,"Reuben Neal","Facilisis Corp.","2021-07-13 08:58",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (66,"Zachary Curry","Amet Ultricies Foundation","2021-07-15 01:19",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (56,"Yolanda Burke","Cras Vehicula Associates","2021-07-15 15:11",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (68,"Lynn Moss","Ac Orci Ut Corp.","2021-07-13 11:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (55,"Victor Mcfadden","Orci Foundation","2021-07-13 00:04",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (36,"Doris Wade","Sit Amet Lorem Limited","2021-07-12 02:30",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (73,"Skyler Sawyer","Ante Ipsum Primis Institute","2021-07-12 06:37",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (18,"Kirby Cross","Libero Est Company","2021-07-14 05:25",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (12,"Lawrence Dudley","Lacus Quisque Imperdiet Limited","2021-07-13 22:07",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (94,"Flavia Blevins","Vulputate Eu Odio Ltd","2021-07-12 12:08",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (4,"Berk Bradford","Tristique Pharetra Quisque Foundation","2021-07-12 18:05",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (28,"Keith Byrd","Scelerisque Associates","2021-07-13 08:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (28,"Ryder Lawrence","Commodo At Libero Consulting","2021-07-15 12:31",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (14,"Clark Stark","Enim Mauris LLP","2021-07-16 12:04",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (52,"Davis Ryan","Non Quam Pellentesque PC","2021-07-15 09:25",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (68,"Kareem Mooney","Dapibus Corporation","2021-07-12 07:29",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (17,"Yoshio Morris","At Pede Cras Incorporated","2021-07-16 17:30",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (48,"Raven Mann","Cursus A Enim Inc.","2021-07-13 12:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (36,"Adria Sanford","Ac Eleifend LLP","2021-07-14 00:18",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (57,"Hedy Burgess","Dis Parturient Montes Institute","2021-07-14 19:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (69,"Illiana Key","Aliquam Ultrices Iaculis Limited","2021-07-16 11:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (22,"Isadora Figueroa","Amet LLC","2021-07-13 22:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (73,"Cole Casey","Lorem Ipsum Corporation","2021-07-12 16:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (37,"Jaquelyn Austin","Eleifend Egestas Sed Associates","2021-07-12 21:44",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (100,"Tarik Poole","Quisque Imperdiet Corp.","2021-07-12 12:04",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (18,"Dieter Thompson","Phasellus Fermentum Corporation","2021-07-13 12:59",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (56,"Linda Buckner","Curabitur Company","2021-07-14 03:26",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (65,"Hammett Maddox","Adipiscing Fringilla Associates","2021-07-12 17:02",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (46,"James Kirby","Erat Etiam Vestibulum LLC","2021-07-12 14:15",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (43,"Cyrus Moody","Urna Nunc Quis LLP","2021-07-15 09:40",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (28,"Rebekah Estes","Nam Interdum Inc.","2021-07-14 04:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (31,"Denise Nixon","Porttitor Industries","2021-07-12 20:07",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (59,"Morgan Guthrie","Consectetuer Foundation","2021-07-12 09:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (95,"Laurel Morse","Aliquet Molestie Company","2021-07-16 13:34",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (60,"Callie Powell","Fermentum Corporation","2021-07-14 12:39",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (71,"Price Robertson","In At Pede Company","2021-07-15 20:01",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (29,"Maya Gonzalez","Pretium Aliquet Metus Associates","2021-07-16 12:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (8,"Louis Dickerson","Eu Dolor Inc.","2021-07-16 02:31",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (86,"Phoebe Thornton","Accumsan Laoreet Incorporated","2021-07-14 11:36",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (85,"Cruz Harper","Nec Incorporated","2021-07-15 04:39",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (52,"Plato Figueroa","Proin Eget Associates","2021-07-14 08:46",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (21,"Anthony Ray","Sagittis Corp.","2021-07-15 07:25",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (72,"Zachery Holden","Lectus Ante Dictum Company","2021-07-16 01:38",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (11,"Lareina Scott","Ante Inc.","2021-07-15 01:32",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (32,"Maxwell Moss","Ante Blandit Viverra Institute","2021-07-16 03:00",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (30,"Noelle Young","Cursus Luctus Ipsum Foundation","2021-07-12 06:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (51,"Ruby Chavez","Eleifend Nec Inc.","2021-07-13 05:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (60,"Gage Crane","Magna Sed Dui Associates","2021-07-14 22:51",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (62,"Keely Lyons","Sit Incorporated","2021-07-13 21:33",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (13,"Rana Rhodes","Neque Ltd","2021-07-16 02:00",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (80,"Salvador Benton","Vivamus Molestie Ltd","2021-07-12 05:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (97,"Leila Greer","In At Pede PC","2021-07-15 05:14",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (30,"Matthew Spears","Ultrices Posuere Cubilia Institute","2021-07-16 13:47",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (12,"Kimberley Rice","Lorem Eu Metus Industries","2021-07-12 22:36",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (54,"Cairo Bartlett","Non Enim Mauris Incorporated","2021-07-16 03:32",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (62,"Zane Cobb","Vivamus Rhoncus Donec PC","2021-07-12 12:49",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (14,"Cameran Bolton","Purus Sapien Incorporated","2021-07-15 21:06",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (61,"Wesley Vaughan","Aliquet Nec Imperdiet Institute","2021-07-15 13:35",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (7,"Reese House","Ante Iaculis Nec Associates","2021-07-15 09:26",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (32,"Baxter Sutton","Phasellus Fermentum PC","2021-07-15 20:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (97,"Derek Landry","Magnis Dis Parturient Limited","2021-07-15 12:21",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (78,"Prescott Davis","Mollis Integer Tincidunt Industries","2021-07-16 15:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (46,"Azalia Dejesus","Nisi Foundation","2021-07-16 09:11",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (21,"Candice Buchanan","Nunc Mauris Foundation","2021-07-15 16:14",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (79,"Daria Moon","Auctor Quis Tristique Corp.","2021-07-16 21:22",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (86,"Madison Baldwin","Tellus Incorporated","2021-07-12 10:37",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (66,"Patrick Deleon","Iaculis Foundation","2021-07-14 19:14",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (61,"Garth Cain","Placerat Consulting","2021-07-13 00:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (96,"Lane Foster","Consectetuer Mauris Associates","2021-07-13 18:14",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (40,"Chaim Garrett","Donec PC","2021-07-14 13:32",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (35,"Steel Mccall","Cursus Institute","2021-07-12 02:37",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (30,"Jessica Lee","Felis Orci Adipiscing Industries","2021-07-15 17:00",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (83,"Hedwig Reyes","Arcu Vestibulum Ut Associates","2021-07-12 13:06",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (21,"Emma Cole","Tincidunt Donec Vitae Incorporated","2021-07-14 21:02",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (25,"Kelsie Patterson","At Pede Cras Limited","2021-07-13 12:49",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (26,"Lacota Johns","Lacinia Vitae Institute","2021-07-13 02:02",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (23,"Myles Clements","Taciti Incorporated","2021-07-14 04:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (67,"Alden Hurst","Facilisis Eget Industries","2021-07-16 11:37",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (23,"Lucian Stewart","Vel Mauris Integer LLP","2021-07-15 19:08",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (82,"Avram Cardenas","Aliquet Nec Incorporated","2021-07-16 19:07",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (65,"Aurora Graham","Lorem Vehicula Company","2021-07-14 05:49",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (100,"Cathleen Pennington","Dis Consulting","2021-07-13 16:34",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (31,"Christine Weber","Ultrices Iaculis Industries","2021-07-15 02:01",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (29,"Stone Gates","Ullamcorper Company","2021-07-16 13:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (88,"Quentin Warren","Magnis Dis Parturient Consulting","2021-07-13 16:21",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (47,"Griffith Garrett","Netus Et Malesuada Corporation","2021-07-15 10:30",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (67,"Barrett Bonner","Volutpat Ornare Corporation","2021-07-16 02:08",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (49,"Hilda Mcdowell","Semper Egestas Urna PC","2021-07-15 13:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (49,"Peter Bates","Dui Lectus Inc.","2021-07-13 19:35",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (84,"Gage Howell","Ornare Associates","2021-07-13 11:20",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (60,"Selma Hunter","Sem Corp.","2021-07-16 14:15",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (25,"Felicia Gilliam","Dui Inc.","2021-07-15 09:49",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (35,"Cain Walters","Ipsum LLC","2021-07-14 06:54",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (51,"Candace Mills","Vitae Inc.","2021-07-15 14:09",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (16,"Bryar Moses","Tempus Associates","2021-07-14 02:29",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (55,"Iona Case","Dictum Proin Industries","2021-07-13 01:05",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (48,"Quintessa Skinner","Fusce Aliquet Magna Incorporated","2021-07-16 07:32",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (74,"Jack Spence","Euismod Mauris Eu Corporation","2021-07-12 01:31",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (58,"Drew Whitehead","Tempus Consulting","2021-07-14 12:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (61,"Sheila Wooten","Ridiculus Mus Proin Limited","2021-07-12 19:21",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (99,"Kiona Greer","Risus Inc.","2021-07-16 22:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (18,"Aimee Doyle","Ante Company","2021-07-15 09:46",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (13,"Dylan Wagner","Lacus Quisque Imperdiet Industries","2021-07-15 09:22",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (48,"Graham Rowe","Non Limited","2021-07-14 09:38",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (43,"Carly Wall","Est LLP","2021-07-12 05:12",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (85,"Hope Kelly","Ullamcorper Magna LLP","2021-07-12 01:54",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (12,"Mira Baker","Metus Eu Institute","2021-07-14 12:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (9,"Erin Estrada","Auctor Non Company","2021-07-14 10:47",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (93,"Rylee Cross","Euismod Et Foundation","2021-07-16 21:37",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (94,"Ashton Atkins","Eu LLP","2021-07-13 23:28",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (46,"Amy Williamson","Interdum Curabitur Company","2021-07-13 13:09",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (29,"Kaseem Blackwell","Duis Foundation","2021-07-16 00:07",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (58,"Sonya Ellison","Nec Orci Consulting","2021-07-14 06:22",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (94,"Gavin Battle","Sollicitudin Consulting","2021-07-14 08:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (68,"Nora Alston","Elementum Dui Quis Consulting","2021-07-13 03:48",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (96,"Philip Mills","Eget Tincidunt PC","2021-07-14 00:34",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (67,"Louis Thompson","At Egestas Ltd","2021-07-12 14:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (11,"Tanisha Salas","Neque Nullam Corp.","2021-07-14 21:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (25,"Kadeem Mitchell","Lobortis Mauris Suspendisse Foundation","2021-07-12 09:33",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (16,"Edan Mcknight","Tellus Justo Sit Limited","2021-07-13 03:58",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (86,"Leroy Sargent","Lorem Vehicula Et LLP","2021-07-13 18:00",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (72,"Maile Delaney","Risus Nulla Incorporated","2021-07-12 18:23",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (67,"Uriel Barron","Sed Sem Inc.","2021-07-16 00:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (21,"Zenaida Knight","Tincidunt Inc.","2021-07-14 14:22",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (69,"Hector Cardenas","Sociis Natoque Limited","2021-07-12 23:03",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (27,"Heather Madden","Diam Lorem Auctor PC","2021-07-12 14:01",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (38,"Rylee White","Proin Limited","2021-07-16 23:25",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (33,"Hillary Rosales","Vulputate Posuere LLP","2021-07-15 10:55",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (91,"Hadassah Johnson","Nulla Tempor Augue Foundation","2021-07-15 00:46",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (48,"Shelby Gregory","Ornare Sagittis Felis Ltd","2021-07-15 08:00",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (55,"Gray Bradshaw","Eu LLC","2021-07-15 14:40",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (90,"Troy Hahn","Malesuada Vel Corp.","2021-07-14 19:02",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (29,"Cameran Hodges","Sed Eu Nibh Company","2021-07-15 19:11",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (92,"David Stewart","Pede Incorporated","2021-07-16 07:40",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (41,"Erich Combs","Magna Sed Corporation","2021-07-16 13:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (66,"Kareem Williamson","Volutpat Incorporated","2021-07-12 19:21",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (63,"Britanney Klein","Blandit Nam Nulla Associates","2021-07-14 14:14",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (8,"Rigel Jenkins","Ipsum LLP","2021-07-14 01:38",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (48,"Silas Padilla","Id Ltd","2021-07-14 20:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (96,"Chaim Carver","Mauris Aliquam Eu Foundation","2021-07-14 03:58",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (7,"Kadeem Hart","Cras Industries","2021-07-15 21:23",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (43,"Nathan Boyer","Sed Congue Elit Incorporated","2021-07-16 06:18",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (24,"Aline Carey","Mauris Company","2021-07-14 09:06",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (93,"Adara Vazquez","In Tincidunt Congue Limited","2021-07-16 10:40",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (13,"Paki Farmer","Morbi Foundation","2021-07-13 18:05",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (79,"Ivy Chavez","Pede Ultrices A Inc.","2021-07-12 10:42",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (100,"Nicole Jarvis","Phasellus Libero Mauris PC","2021-07-13 16:05",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (9,"Eagan Rich","Ultrices Mauris Corp.","2021-07-14 02:51",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (38,"Yetta Mathis","Id Magna LLC","2021-07-14 17:54",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (65,"Alexandra Velazquez","Vitae Aliquet Nec Corp.","2021-07-12 12:53",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (18,"Elton Snyder","Ut Quam Industries","2021-07-15 04:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (23,"Phelan Hinton","Dui Nec Tempus Industries","2021-07-14 23:11",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (60,"Valentine Stewart","Dapibus Incorporated","2021-07-13 23:26",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (93,"Trevor Davidson","Ullamcorper Ltd","2021-07-15 04:47",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (50,"Samuel Cruz","Feugiat Industries","2021-07-12 12:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (41,"Acton Witt","Curabitur Sed Institute","2021-07-14 00:41",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (90,"Abigail Goodman","Ultrices LLP","2021-07-15 20:29",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (47,"Price Downs","Phasellus Fermentum Industries","2021-07-14 20:05",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (4,"Abra Bass","Vel Nisl Quisque Limited","2021-07-15 13:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (51,"Garrison Whitfield","Hendrerit Consectetuer Cursus Industries","2021-07-13 09:24",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (7,"Garrison Duffy","Egestas Sed Pharetra Inc.","2021-07-15 09:35",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (5,"Katell Bender","Consectetuer Adipiscing Elit Foundation","2021-07-16 10:25",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (49,"Katell Hubbard","Ipsum Dolor Company","2021-07-14 03:45",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (85,"Tatiana Ramsey","Libero Dui Nec Ltd","2021-07-15 17:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (13,"Martha Delgado","Nulla Tempor Augue Corp.","2021-07-13 05:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (67,"Cherokee Chavez","Etiam Laoreet Libero Corporation","2021-07-14 02:48",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (65,"Rachel Mcdowell","Iaculis Nec Limited","2021-07-12 01:01",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (25,"Cailin Goodwin","Nec Tellus Nunc Foundation","2021-07-14 11:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (63,"Elizabeth Hansen","Posuere Enim Nisl Limited","2021-07-12 04:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (56,"Kimberly Dudley","Quam A Corporation","2021-07-12 09:46",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (57,"Sopoline Buck","Vitae Risus Corp.","2021-07-16 07:23",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (27,"Julian Patterson","Maecenas Libero Inc.","2021-07-14 13:15",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (28,"Robert Decker","Non Ante Bibendum Company","2021-07-14 08:57",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (64,"Yolanda French","Ut Sem Nulla Inc.","2021-07-14 20:50",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (81,"Cameran Daniel","Vel Lectus Foundation","2021-07-16 06:18",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (80,"Maxine Wilkerson","Eu Industries","2021-07-15 22:27",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (100,"Julie Mcconnell","Sodales Elit Associates","2021-07-14 11:29",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (71,"Kelly Rich","Pede Cras Institute","2021-07-12 02:52",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (5,"Lenore Bradley","Luctus Incorporated","2021-07-12 10:36",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (14,"Craig Lindsay","Mauris Consulting","2021-07-16 20:35",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (21,"Courtney Walter","Sollicitudin LLP","2021-07-13 19:20",1);
INSERT INTO `encomendas` (`morador_id`,`destinatario`,`remetente`,`data_recebimento`,`porteiro_recebeu`) VALUES (72,"Aladdin Cannon","Suscipit Est Industries","2021-07-13 15:04",1);
